// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9tL7SqL-mrFKItueDRR8xQ1GY69JM2A4',
    appId: '1:1055851081626:web:31768554b79c5649c21423',
    messagingSenderId: '1055851081626',
    projectId: 'walkie-7a9dc',
    authDomain: 'walkie-7a9dc.firebaseapp.com',
    storageBucket: 'walkie-7a9dc.firebasestorage.app',
    measurementId: 'G-1L0JB28SN5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe7Rok4FnqB7S5hlotfxEao5JlfO_IL-E',
    appId: '1:1055851081626:android:8e80a24580b6fe7ac21423',
    messagingSenderId: '1055851081626',
    projectId: 'walkie-7a9dc',
    storageBucket: 'walkie-7a9dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyXSucEiDJESPU6elNm74fW-QTdJ3bAis',
    appId: '1:1055851081626:ios:062433186d18d7fdc21423',
    messagingSenderId: '1055851081626',
    projectId: 'walkie-7a9dc',
    storageBucket: 'walkie-7a9dc.firebasestorage.app',
    iosBundleId: 'com.baust.eventmanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyXSucEiDJESPU6elNm74fW-QTdJ3bAis',
    appId: '1:1055851081626:ios:062433186d18d7fdc21423',
    messagingSenderId: '1055851081626',
    projectId: 'walkie-7a9dc',
    storageBucket: 'walkie-7a9dc.firebasestorage.app',
    iosBundleId: 'com.baust.eventmanager',
  );
}

